[config]
schemaVersion = "0.0.1"

[package]
namespace = "jakobhellermann"
name = "DubiDebugMod"
versionNumber = "0.1.0"
description = "Basic Debug Mod with Savestates"
websiteUrl = "https://github.com/jakobhellermann/NineSols-DebugModPlus"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2303"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = ["hollow-knight-silksong"]
